[package]
name = "patchling"
version = "0.1.0"
authors = ["Alissa Rao <lymia@lymiahugs.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
mlua = { version = "0.5", features = ["luajit", "vendored", "send", "serde"] }
serde = { version = "1.0", features = ["derive"] }
