[package]
name = "patchling_cli"
version = "0.1.0"
authors = ["Alissa Rao <lymia@lymiahugs.com>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
serde_json = "1.0.64"

patchling = { path = "../patchling" }
